name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Create public
        run: |
          mkdir public
          mv ./index.html ./dist ./public
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          commit_message: "Deploy to GitHub Pages"
          cname: html-to-docx-js-client-demo.termian.dev